from django.db import models

# Create your models here.
class BossExpUser(models.Model):
	Uin = models.BigIntegerField(primary_key=True)
	NickName = models.CharField(max_length=128, blank=True, default='')
	ShopName = models.CharField(max_length=128, blank=True, default='')
	AuditFlag = models.IntegerField(blank=True, default=0)
	AuditMsg = models.CharField(max_length=256, blank=True, default='')
	AuditTimeMs = models.BigIntegerField(blank=True, default=0)
	BalFlag = models.IntegerField(blank=True, default=0)
	VBalFlag = models.IntegerField(blank=True, default=0)
	BLDate = models.IntegerField(blank=True, default=0)
	Property = models.IntegerField(blank=True, default=0)
	DelFlag = models.IntegerField(blank=True, default=0)
	PlanModTimes = models.IntegerField(blank=True, default=0)
	AdSpecLimit = models.CharField(max_length=1024, blank=True, default='')
	Pro2AddTime = models.IntegerField(blank=True, default=0)
	Pro2DelTime = models.IntegerField(blank=True, default=0)
	InsertTimeMs = models.BigIntegerField(blank=True, default=0) 
	PreModTimeMs = models.BigIntegerField(blank=True, default=0) 
	LastModTimeMs = models.BigIntegerField(blank=True, default=0) 
	ExpandStr = models.CharField(max_length=256, blank=True, default='')
	ModBy = models.CharField(max_length=256, blank=True, default='')
	UserType = models.IntegerField(blank=True, default=0)
	JdCompanyName = models.CharField(max_length=256, blank=True, default='')
	JdShopName = models.CharField(max_length=256, blank=True, default='')
	JdShopId = models.CharField(max_length=64, blank=True, default='')
	JdShopUrl = models.CharField(max_length=512, blank=True, default='')
	JdShopNavId = models.IntegerField(blank=True, default=0)
	JdShopNavName = models.CharField(max_length=256, blank=True, default='')
	GdtUId = models.BigIntegerField(blank=True, default=0)
	JdSupplierId = models.CharField(max_length=64, blank=True, default='')
	JdSupplierNavId = models.IntegerField(blank=True, default=0)
	JdSupplierNavName = models.CharField(max_length=256, blank=True, default='')
	ProductLimit = models.CharField(max_length=1024, blank=True, default='')
	JdClassL3Ids = models.CharField(max_length=1024, blank=True, default='')
	JdClassL3Names = models.CharField(max_length=1024, blank=True, default='')
	UserName = models.CharField(max_length=128, blank=True, default='')
	UserGender = models.IntegerField(blank=True, default=0)
	QQNumber = models.BigIntegerField(blank=True, default=0)
	PhoneNumber = models.CharField(max_length=64, blank=True, default='')
	VerifyPhoneTimes = models.BigIntegerField(blank=True, default=0)
	EMailAddress = models.CharField(max_length=256, blank=True, default='')
	VerifyEMailTimes = models.BigIntegerField(blank=True, default=0)
	MsgChannel = models.BigIntegerField(blank=True, default=0)
	JtmfTagsLimit = models.CharField(max_length=512, blank=True, default='')
	CrowdLimit = models.IntegerField(blank=True, default=0)
	CrowdQuota = models.BigIntegerField(blank=True, default=0)
	OmgUId = models.BigIntegerField(blank=True, default=0)
	ParentUin = models.BigIntegerField(blank=True, default=0)
	MasterFlag = models.IntegerField(blank=True, default=0)
	FundType = models.IntegerField(blank=True, default=0)
	Department = models.CharField(max_length=1024, blank=True, default='')
	class Meta:
		db_table = 'BossExpUser'